[build]
compile = './mvnw compile'
clean = './mvnw clean'

[test]
run_all = './mvnw test'
run_single = './mvnw test -Dtest={testName}'

[parse]
error_regex = '(?m)^\[ERROR\] (.*)$'
test_failure_regex = '(?m)^\s*([\w.]+)\s+Time elapsed:'
